version: 2
jobs:
  test_random_forest_model:
    working_directory: ~/project
    docker:
<<<<<<< HEAD
      - image: circleci/python:3.7.2
=======
      - image: circleci/python:3.8.6
>>>>>>> 3cb06b40f4784395e96a99ce701cbb0988c1da85
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/random_forest_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/random_forest_model/tests
workflows:
  version: 2
  test-all:
    jobs:
      - test_random_forest_model